path:
  data_path_train: /content/my_little_dataset/train
  data_path_val: /content/my_little_dataset/val
  data_path_test: /content/my_little_dataset/test
  result_path_model: /content/mytraining.pt
  logs_tensorboard: ./runs/test_1

general:
  seed: 0

train:
  num_epochs: 10
  learning_rate: 0.001
  weight_decay: 0.00001
  batch_size: 2
  num_workers: 2
