path:
  data_path_train: ./../my_little_dataset/train
  data_path_val: ./../my_little_dataset/val
  data_path_test: ./../my_little_dataset/test
  result_path: results/
  logs_tensorboard: ./runs/test_1

general:
  use_cuda: Yes
  seed: 0

train:
  num_epochs: 5
  learning_rate: 0.001
  weight_decay: 0.00001
  batch_size: 2
  num_workers: 2
