path:
  data_path: ./../my_little_dataset
  result_path: results/
  logs_tensorboard: ./runs/test_1

general:
  use_cuda: Yes
  seed: 0

train:
  num_epochs: 5
  learning_rate: 0.001
  weight_decay: 0.00001
  batch_size: 64
  num_workers: 2
