path:
  data_path: config/config.yaml
  result_path: results/

general:
  use_cuda: Yes
  seed: 0

train:
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.00001
  batch_size: 64
  num_workers: 2
