path:
  data_path_realtrain: ../DeepMaterialsData/trainBlended
  data_path_train: ../trainon2
  data_path_val: ../valon1
  data_path_test: content/my_little_dataset/test
  result_path_model: ../../mytraining1b.pt
  logs_tensorboard: ../runs/test1b
  load_path: ../../mytraining1b.pt

general:
  seed: 0

train:
  num_epochs: 2       #number of epochs
  learning_rate: 0.00002      #learning rate for optimizer
  weight_decay: 0.000000001     #régularisation
  batch_size: 1            #size of batch
  num_workers: 2            #number of workers
  trainset_division: 1000    #trainset too big so we divide it in 100
  real_training: False
  loss: 'l1'   #or 'rendering' or 'deep' or 'deep_rendering'